
services:
  api:
    build: .
    container_name: finance_api  
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy  
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "alembic upgrade head &&
             python -m uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    networks:
      - app_network

  db:
    image: postgres:17
    container_name: finance_db 
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge